### ISSUE TITLE
Shell error when using this flake on aarch64-darwin

### ISSUE THREAD

**Issue by dvtkrlbs** [maximoffua/flutter.nix#12]
```
/private/tmp/nix-build-flutter-tools-3.19.6.drv-1/source/packages/flutter_tools
@nix { "action": "setPhase", "phase": "updateAutotoolsGnuConfigScriptsPhase" }
Running phase: updateAutotoolsGnuConfigScriptsPhase
@nix { "action": "setPhase", "phase": "configurePhase" }
Running phase: configurePhase
no configure script, doing nothing
Executing dartConfigHook
Setting up SDK
Installing dependencies
Finished dartConfigHook
@nix { "action": "setPhase", "phase": "buildPhase" }
Running phase: buildPhase
Executing dartBuildHook
Executing dartBuildHook
Compiling bin/flutter_tools.dart to jit-snapshot file flutter_tools.snapshot.
Unhandled exception:
Invalid argument (NIX_FLUTTER_HOST_PLATFORM): Unknown Nix host platform!: "aarch64-darwin"
#0      new _PosixUtils (package:flutter_tools/src/base/os.dart:270:21)
#1      new _MacOSUtils (package:flutter_tools/src/base/os.dart)
#2      new OperatingSystemUtils (package:flutter_tools/src/base/os.dart:32:14)
#3      runInContext.<anonymous closure> (package:flutter_tools/src/context_runner.dart:307:35)
#4      AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:107:42)
#5      _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:543:23)
#6      AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:95:20)
#7      AppContext.get (package:flutter_tools/src/base/context.dart:124:32)
#8      os (package:flutter_tools/src/globals.dart:66:40)
#9      runInContext.<anonymous closure> (package:flutter_tools/src/context_runner.dart:162:26)
#10     AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:107:42)
#11     _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:543:23)
#12     AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:95:20)
#13     AppContext.get (package:flutter_tools/src/base/context.dart:124:32)
#14     cache (package:flutter_tools/src/globals.dart:57:28)
#15     runInContext.<anonymous closure> (package:flutter_tools/src/context_runner.dart:142:24)
#16     AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:107:42)
#17     _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:543:23)
#18     AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:95:20)
#19     AppContext.get (package:flutter_tools/src/base/context.dart:124:32)
#20     artifacts (package:flutter_tools/src/globals.dart:55:37)
#21     generateCommands (package:flutter_tools/executable.dart:155:24)
#22     main.<anonymous closure> (package:flutter_tools/executable.dart:92:11)
#23     run.<anonymous closure> (package:flutter_tools/runner.dart:53:13)
<asynchronous suspension>
#24     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#25     main (package:flutter_tools/executable.dart:90:3)
<asynchronous suspension>
/nix/store/h3f3f6z54p6rkkvs104mbsqz7izp1ips-stdenv-darwin/setup: line 1588: pop_var_context: head of shell_variables not a function context
```

**Comment by dvtkrlbs** [comment]
sorry for the non highlighted content causing bunch of issue mentions
